name: publish
run-name: Update files on rustytanton.com
on:
  push:
    branches:
      - 'master'

env:
  NODE_VERSION: 22

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: rustytanton.com
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install NodeJS dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test
      
      - name: Build
        run: npm run build

      - name: SCP files to web server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          source: ./dist/scripts.js.LICENSE.txt
          target: ~/
          use_insecure_cipher: true
          overwrite: true