name: publish
run-name: Update files on rustytanton.com
on:
  push:
    branches:
      - 'master'

env:
  NODE_VERSION: 22

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: rustytanton.com
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install NodeJS dependencies
        run: npm ci

      - name: Lint CSS
        run: npm run lintcss

      - name: Lint JS
        run: npm run lintjs
      
      - name: Minify CSS
        run: npm run minifycss && rm ${GITHUB_WORKSPACE}/public_html/styles.css
      
      - name: Minify JS
        run: npm run minifyjs && rm ${GITHUB_WORKSPACE}/public_html/index.js

      - name: index.html token substitution
        run: |
          sed -i "s/{{DATE_TODAY}}/$(date +'%b %e, %Y')/g" ${GITHUB_WORKSPACE}/public_html/index.html
          sed -i "s/{{VERSION}}/$(date +'%s')/g" ${GITHUB_WORKSPACE}/public_html/index.html
      
      - name: sitemap.xml token substitution
        run: |
            sed -i "s/{{LASTMOD}}/$(date +'%Y-%m-%d')/g" ${GITHUB_WORKSPACE}/public_html/sitemap.xml

      - name: SCP files to web server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          source: public_html/*
          target: ~/
          use_insecure_cipher: true
          overwrite: true