name: publish
run-name: Update files on rustytanton.com
on:
  push:
    branches:
      - 'master'
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: rustytanton.com
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: index.html token substitution
        run: |
          sed -i "s/{{DATE_TODAY}}/$(date +'%b %e, %Y')/g" ${GITHUB_WORKSPACE}/public_html/index.html

      - name: SCP files to web server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          source: public_html/*
          target: ~/public_html
          use_insecure_cipher: true