name: publish
run-name: Update files on rustytanton.com
on:
  push:
    branches:
      - 'master'
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: rustytanton.com
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: index.html token substitution
        run: |
          sed -i "s/{{DATE_TODAY}}/$(date +'%b %e, %Y')/g" ${GITHUB_WORKSPACE}/public_html/index.html
      - name: SCP files to web server
        run: |
          scp -rp ${GITHUB_WORKSPACE}/public_html/* ${WEBHOST_USER}@${WEBHOST_DOMAIN}:${WEBHOST_ROOT}/
        env:
          WEBHOST_USER: ${{ secrets.WEBHOST_USER }}
          WEBHOST_DOMAIN: ${{ secrets.WEBHOST_DOMAIN }}
          WEBHOST_ROOT: ${{ secrets.WEBHOST_ROOT }}